apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: test-kubernetes 
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
      app: test-kubernetes-label 
  template: 
    metadata: 
      labels: 
        app: test-kubernetes-label 
    spec: 
      containers: 
      - name: test-kubernetes-container 
        image: hoehne/test-kubernetes:first-test 
        ports: 
        - containerPort: 8080
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: test-kubernetes-service 
spec:
  type: NodePort 
  selector: 
    app: test-kubernetes-label
  ports: 
  - port: 8080
    targetPort: 8080
    nodePort: 30000 
  